default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_kadai_development

test:
  <<: *default
  database: rails_kadai_test

production:
  <<: *default
  database: rails_kadai_production
  username: rails_kadai
  password: <%= ENV['RAILS_KADAI_DATABASE_PASSWORD'] %>
